# Generated by Django 2.2 on 2021-03-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessegeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='groups.Message')),
            ],
        ),
    ]
